export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount';
export const DAEMON = '@@saga-injector/daemon';
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount';

export const colorMap = [
  '#ffffe0',
  '#fffddb',
  '#fffad7',
  '#fff7d1',
  '#fff5cd',
  '#fff2c8',
  '#fff0c4',
  '#ffedbf',
  '#ffebba',
  '#ffe9b7',
  '#ffe5b2',
  '#ffe3af',
  '#ffe0ab',
  '#ffdda7',
  '#ffdba4',
  '#ffd9a0',
  '#ffd69c',
  '#ffd399',
  '#ffd196',
  '#ffcd93',
  '#ffca90',
  '#ffc88d',
  '#ffc58a',
  '#ffc288',
  '#ffbf86',
  '#ffbd83',
  '#ffb981',
  '#ffb67f',
  '#ffb47d',
  '#ffb17b',
  '#ffad79',
  '#ffaa77',
  '#ffa775',
  '#ffa474',
  '#ffa172',
  '#ff9e70',
  '#ff9b6f',
  '#ff986e',
  '#ff956c',
  '#fe916b',
  '#fe8f6a',
  '#fd8b69',
  '#fc8868',
  '#fb8567',
  '#fa8266',
  '#f98065',
  '#f87d64',
  '#f77a63',
  '#f67862',
  '#f57562',
  '#f37261',
  '#f37060',
  '#f16c5f',
  '#f0695e',
  '#ee665d',
  '#ed645c',
  '#ec615b',
  '#ea5e5b',
  '#e85b59',
  '#e75859',
  '#e55658',
  '#e45356',
  '#e35056',
  '#e14d54',
  '#df4a53',
  '#dd4852',
  '#db4551',
  '#d9434f',
  '#d8404e',
  '#d53d4d',
  '#d43b4b',
  '#d2384a',
  '#cf3548',
  '#cd3346',
  '#cc3045',
  '#ca2e43',
  '#c72b42',
  '#c52940',
  '#c2263d',
  '#c0233c',
  '#be213a',
  '#bb1e37',
  '#ba1c35',
  '#b71933',
  '#b41731',
  '#b2152e',
  '#b0122c',
  '#ac1029',
  '#aa0e27',
  '#a70b24',
  '#a40921',
  '#a2071f',
  '#a0051c',
  '#9d0419',
  '#990215',
  '#970212',
  '#94010e',
  '#91000a',
  '#8e0006',
  '#8b0000',
];

export const countryNames = [
  'Afghanistan',
  'Angola',
  'Albania',
  'United Arab Emirates',
  'Argentina',
  'Armenia',
  'Fr. S. Antarctic Lands',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Burundi',
  'Belgium',
  'Benin',
  'Burkina Faso',
  'Bangladesh',
  'Bulgaria',
  'Bahamas',
  'Bosnia and Herz.',
  'Belarus',
  'Belize',
  'Bolivia',
  'Brazil',
  'Brunei',
  'Bhutan',
  'Botswana',
  'Central African Rep.',
  'Canada',
  'Switzerland',
  'Chile',
  'China',
  'Côte d\'Ivoire',
  'Cameroon',
  'Dem. Rep. Congo',
  'Congo',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'N. Cyprus',
  'Cyprus',
  'Czechia',
  'Germany',
  'Djibouti',
  'Denmark',
  'Dominican Rep.',
  'Algeria',
  'Ecuador',
  'Egypt',
  'Eritrea',
  'Spain',
  'Estonia',
  'Ethiopia',
  'Finland',
  'Fiji',
  'Falkland Is.',
  'France',
  'Gabon',
  'United Kingdom',
  'Georgia',
  'Ghana',
  'Guinea',
  'Gambia',
  'Guinea-Bissau',
  'Eq. Guinea',
  'Greece',
  'Greenland',
  'Guatemala',
  'Guyana',
  'Honduras',
  'Croatia',
  'Haiti',
  'Hungary',
  'Indonesia',
  'India',
  'Ireland',
  'Iran',
  'Iraq',
  'Iceland',
  'Israel',
  'Italy',
  'Jamaica',
  'Jordan',
  'Japan',
  'Kazakhstan',
  'Kenya',
  'Kyrgyzstan',
  'Cambodia',
  'South Korea',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lebanon',
  'Liberia',
  'Libya',
  'Sri Lanka',
  'Lesotho',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Morocco',
  'Moldova',
  'Madagascar',
  'Mexico',
  'Macedonia',
  'Mali',
  'Myanmar',
  'Montenegro',
  'Mongolia',
  'Mozambique',
  'Mauritania',
  'Malawi',
  'Malaysia',
  'Namibia',
  'New Caledonia',
  'Niger',
  'Nigeria',
  'Nicaragua',
  'Netherlands',
  'Norway',
  'Nepal',
  'New Zealand',
  'Oman',
  'Pakistan',
  'Panama',
  'Peru',
  'Philippines',
  'Papua New Guinea',
  'Poland',
  'Puerto Rico',
  'North Korea',
  'Portugal',
  'Paraguay',
  'Palestine',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'W. Sahara',
  'Saudi Arabia',
  'Sudan',
  'S. Sudan',
  'Senegal',
  'Solomon Is.',
  'Sierra Leone',
  'El Salvador',
  'Somaliland',
  'Somalia',
  'Serbia',
  'Suriname',
  'Slovakia',
  'Slovenia',
  'Sweden',
  'Swaziland',
  'Syria',
  'Chad',
  'Togo',
  'Thailand',
  'Tajikistan',
  'Turkmenistan',
  'Timor-Leste',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Taiwan',
  'Tanzania',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'United States',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Vanuatu',
  'Yemen',
  'South Africa',
  'Zambia',
  'Zimbabwe',
];
